### ISSUE TITLE
Multi-instance support does not work

### ISSUE THREAD

**Issue by btiller123** [sibiraj-s/angular-paginator#6]
I'm using the package on two different web pages, and find that values such as paginator.pages are corrupted when more than one instance of the package is in use.  When I tried to specify a different id for each instance, the packages complains that valid id ANGULAR_PAGINATOR_DEFAULT was not found.  My implementation is the same as what's shown in stackblitz except that I have it on two separate pages.  If I remove the implementation from one page, the other works fine, but I need it to work on two pages.

I'm using Angular 16.1.4 with angular-paginator 11.0.0.

**Comment by andresliu-p202** [comment]
@btiller123 I'm running into a similar issue. Did you find a solution?

**Comment by andresliu-p202** [comment]
It seems like the only way this library registers an instance is by using the `angularPaginator` pipe, so I had to render an invisible, dummy element that utilizes it alongside the template of my actual custom pagination component.

````
<div
  *ngFor="
    let item of totalCountArray
      | angularPaginator
        : { itemsPerPage: pageSize, currentPage: index, id: id }
  "
  style="display: none"
  aria-hidden="true"
></div>
````

**Comment by sibiraj-s** [comment]
Hi, Sorry for the delayed response. I'll look into this this weekend. 

Feel free to post solutions if any meanwhile. 

I am considering to move to new standalone components, It might fix things, not sure atm.

**Comment by sibiraj-s** [comment]
Hi. Sorry for the delay. Can you share a reproducible example? I am unable to reproduce this, may be I am doing something different. An example would be better. Either a Stackblitz or a GitHub works.

**Comment by sibiraj-s** [comment]
I am sorry for the delayed response, caught up with personal things.

That error mentioned is the a result of the `id` being provided just the pipe and not the directive. You'll need to provide same id for both directive and the pipe of an instance, else this error would happen. This is the same case for single and multiple instances.

I'll update this in README as well.
